apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    name: nginx-dns
  name: nginx-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-dns-pod
  template:
    metadata:
      labels:
        app: nginx-dns-pod
    spec:
      containers:
      - image: nginx
        name: nginx
